// Built-in sample listings used when Supabase is unreachable.
import { filterListingRows, mergeAndPaginateListings } from './listingQuery';

const DEMO_LISTINGS = [
  {
    id: 'demo-1',
    name: 'Agilent 1260 Infinity II HPLC',
    spec: 'Quaternary pump, DAD detector, autosampler',
    condition: 'USED',
    price: 28500,
    negotiable: true,
    source_name: 'LabX.com',
    source_url: 'https://www.labx.com',
    contact_name: 'LabX Seller',
    contact_email: 'sales@labx.com',
    year: 2019,
    category: 'Analytical',
    tags: ['hplc'],
    is_active: true,
    created_at: '2025-11-01T10:00:00.000Z',
  },
  {
    id: 'demo-2',
    name: 'Waters Xevo TQ-S Micro LC-MS/MS',
    spec: 'Triple quadrupole mass spec with Acquity UPLC',
    condition: 'USED',
    price: 95000,
    negotiable: true,
    source_name: 'BioSurplus.com',
    source_url: 'https://www.biosurplus.com',
    contact_name: 'BioSurplus Sales',
    contact_email: 'sales@biosurplus.com',
    year: 2018,
    category: 'Analytical',
    tags: ['lc-ms', 'mass spec'],
    is_active: true,
    created_at: '2025-10-15T10:00:00.000Z',
  },
  {
    id: 'demo-3',
    name: 'Eppendorf 5810R Centrifuge',
    spec: 'Refrigerated benchtop centrifuge, 4L capacity',
    condition: 'USED',
    price: 4200,
    negotiable: false,
    source_name: 'EquipNet.com',
    source_url: 'https://www.equipnet.com',
    contact_name: 'EquipNet Sales',
    contact_email: 'sales@equipnet.com',
    year: 2017,
    category: 'Biology',
    tags: ['centrifuge'],
    is_active: true,
    created_at: '2025-09-20T10:00:00.000Z',
  },
  {
    id: 'demo-4',
    name: 'Hamilton STAR Liquid Handler',
    spec: '96-channel automated liquid handling platform',
    condition: 'USED',
    price: 120000,
    negotiable: true,
    source_name: 'LabX.com',
    source_url: 'https://www.labx.com',
    contact_name: 'LabX Seller',
    contact_email: 'sales@labx.com',
    year: 2020,
    category: 'Drug Discovery',
    tags: ['liquid handler', 'hts'],
    is_active: true,
    created_at: '2025-08-05T10:00:00.000Z',
  },
  {
    id: 'demo-5',
    name: 'Sartorius Biostat STR 200L',
    spec: 'Single-use bioreactor for upstream processing',
    condition: 'NEW',
    price: 185000,
    negotiable: false,
    source_name: 'BioSurplus.com',
    source_url: 'https://www.biosurplus.com',
    contact_name: 'BioSurplus Sales',
    contact_email: 'sales@biosurplus.com',
    year: 2024,
    category: 'Life Science',
    tags: ['bioreactor'],
    is_active: true,
    created_at: '2025-12-01T10:00:00.000Z',
  },
  {
    id: 'demo-6',
    name: 'Bruker AVANCE NEO 400 MHz NMR',
    spec: 'NMR spectrometer with autosampler and cryoprobe',
    condition: 'USED',
    price: 310000,
    negotiable: true,
    source_name: 'LabX.com',
    source_url: 'https://www.labx.com',
    contact_name: 'LabX Seller',
    contact_email: 'sales@labx.com',
    year: 2016,
    category: 'Analytical',
    tags: ['nmr'],
    is_active: true,
    created_at: '2025-07-12T10:00:00.000Z',
  },
  {
    id: 'demo-7',
    name: 'Beckman Coulter CytoFLEX S Flow Cytometer',
    spec: '13-color flow cytometry system',
    condition: 'USED',
    price: 78000,
    negotiable: true,
    source_name: 'EquipNet.com',
    source_url: 'https://www.equipnet.com',
    contact_name: 'EquipNet Sales',
    contact_email: 'sales@equipnet.com',
    year: 2019,
    category: 'Biology',
    tags: ['flow cytometer'],
    is_active: true,
    created_at: '2025-06-18T10:00:00.000Z',
  },
  {
    id: 'demo-8',
    name: 'PerkinElmer EnVision Plate Reader',
    spec: 'Multimode microplate reader for HTS assays',
    condition: 'USED',
    price: 22000,
    negotiable: true,
    source_name: 'BioSurplus.com',
    source_url: 'https://www.biosurplus.com',
    contact_name: 'BioSurplus Sales',
    contact_email: 'sales@biosurplus.com',
    year: 2018,
    category: 'Drug Discovery',
    tags: ['plate reader', 'hts'],
    is_active: true,
    created_at: '2025-05-30T10:00:00.000Z',
  },
];

export function queryDemoListings(params) {
  const rows = filterListingRows(DEMO_LISTINGS, params);
  return { ...mergeAndPaginateListings(rows, params), demo: true };
}
